# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160115151452 on 2016-01-16 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitlet', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweetlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=140)),
            ],
        ),
    ]
