# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160115151452 on 2016-01-17 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitlet', '0004_tweetlet_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetlet',
            name='user',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
