# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20160115151452 on 2016-01-19 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitlet', '0006_remove_tweetlet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetlet',
            name='user',
            field=models.CharField(default='anonymous', max_length=140),
            preserve_default=False,
        ),
    ]
